"""
VortexL2 HAProxy Manager

Manages HAProxy configuration for TCP port forwarding.
"""

import subprocess
import logging
import shutil
from pathlib import Path
from typing import List, Tuple, Dict, Optional

logger = logging.getLogger(__name__)

from vortexl2.config import ConfigManager

HAPROXY_CONFIG_DIR = Path("/etc/haproxy")
HAPROXY_CONFIG_FILE = HAPROXY_CONFIG_DIR / "haproxy.cfg"
HAPROXY_BACKUP_FILE = HAPROXY_CONFIG_DIR / "haproxy.cfg.bak"


class HAProxyManager:
    """Manages HAProxy for port forwarding."""

    def __init__(self, config=None):
        self.config = config
        self.haproxy_config_path = HAPROXY_CONFIG_FILE
        self.running = False

    def _generate_haproxy_config(self) -> str:
        """Generate HAProxy configuration for all configured tunnels."""
        config = """# HAProxy configuration generated by VortexL2
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    # BUG FIX #8: Add maxconn to prevent fd exhaustion under load
    maxconn 50000

defaults
    log     global
    mode    tcp
    option  tcplog
    option  dontlognull
    # BUG FIX #9: Added tcp-check for backend health detection
    option  tcp-check
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    # BUG FIX #10: Add retries to handle transient backend failures
    retries 3

"""
        config_manager = ConfigManager()
        tunnels = config_manager.get_all_tunnels()

        if not tunnels:
            return config

        # BUG FIX #11: Track ports to avoid duplicate frontend/backend definitions
        # when multiple tunnels share the same port (causes haproxy parse error)
        seen_ports = set()

        for tunnel in tunnels:
            remote_ip = getattr(tunnel, 'remote_forward_ip', None)
            tunnel_name = tunnel.name
            if not remote_ip:
                logger.debug(f"Skipping tunnel {tunnel_name}: no remote_forward_ip")
                continue
            if not getattr(tunnel, 'forwarded_ports', None):
                logger.debug(f"Skipping tunnel {tunnel_name}: no forwarded_ports")
                continue

            for port in tunnel.forwarded_ports:
                if port in seen_ports:
                    logger.warning(
                        f"Port {port} already defined (tunnel {tunnel_name}); skipping duplicate"
                    )
                    continue
                seen_ports.add(port)

                config += f"""frontend frontend_{port}
    bind *:{port}
    default_backend backend_{port}

backend backend_{port}
    server server_{port} {remote_ip}:{port} check

"""
        return config

    def _write_config_file(self, config_content: str) -> bool:
        """Write HAProxy configuration to file."""
        try:
            HAPROXY_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

            if HAPROXY_CONFIG_FILE.exists() and not HAPROXY_BACKUP_FILE.exists():
                shutil.copy2(HAPROXY_CONFIG_FILE, HAPROXY_BACKUP_FILE)
                logger.info(f"Backed up original HAProxy config to {HAPROXY_BACKUP_FILE}")

            # BUG FIX #12: Write to a temp file, validate, then atomically replace.
            # Avoids truncating the live config on a crash mid-write.
            tmp_file = HAPROXY_CONFIG_FILE.with_suffix(".cfg.tmp")
            with open(tmp_file, 'w') as f:
                f.write(config_content)

            # Validate config before replacing
            result = subprocess.run(
                ["haproxy", "-c", "-f", str(tmp_file)],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode != 0:
                logger.error(f"HAProxy config validation failed: {result.stderr.strip()}")
                tmp_file.unlink(missing_ok=True)
                return False

            tmp_file.replace(HAPROXY_CONFIG_FILE)
            logger.info(f"Generated and validated HAProxy config: {HAPROXY_CONFIG_FILE}")
            return True

        except Exception as e:
            logger.error(f"Failed to write HAProxy config: {e}")
            return False

    def _reload_haproxy(self) -> bool:
        """Reload HAProxy configuration gracefully."""
        try:
            # BUG FIX #13: Prefer `reload` over `restart` to avoid connection drops.
            # Fall back to restart only if reload isn't supported.
            result = subprocess.run(
                ["systemctl", "reload-or-restart", "haproxy"],
                capture_output=True, timeout=15, text=True
            )

            if result.returncode == 0:
                logger.info("HAProxy reloaded successfully")
                return True

            logger.error(f"HAProxy reload-or-restart failed: {result.stderr.strip()}")
            return False

        except subprocess.TimeoutExpired:
            logger.error("HAProxy reload timeout")
            return False
        except Exception as e:
            logger.error(f"Failed to reload HAProxy: {e}")
            return False

    def _is_port_listening(self, port: int) -> bool:
        """Check if a port is listening."""
        try:
            result = subprocess.run(
                f"ss -tlnp 2>/dev/null | grep -E ':{port}\\b'",
                shell=True, capture_output=True, timeout=5
            )
            return result.returncode == 0
        except Exception:
            return False

    def _get_port_process(self, port: int) -> Optional[str]:
        """Get the process using a specific port."""
        try:
            result = subprocess.run(
                f"lsof -i :{port} -t 2>/dev/null | head -1",
                shell=True, capture_output=True, timeout=5, text=True
            )
            if result.returncode == 0 and result.stdout.strip():
                pid = result.stdout.strip()
                ps_result = subprocess.run(
                    f"ps -p {pid} -o comm=",
                    shell=True, capture_output=True, timeout=5, text=True
                )
                if ps_result.returncode == 0 and ps_result.stdout.strip():
                    return f"{ps_result.stdout.strip()} (PID: {pid})"
                return f"PID: {pid}"
            return None
        except Exception:
            return None

    # BUG FIX #14: parse_ports extracted as a shared utility to eliminate duplication
    @staticmethod
    def _parse_ports(ports_str: str) -> Tuple[bool, List[int], str]:
        """Parse port string (e.g. '443,8080,9000-9005') into list of ints."""
        ports = []
        try:
            for part in ports_str.split(','):
                part = part.strip()
                if not part:
                    continue
                if '-' in part:
                    start, end = map(int, part.split('-', 1))
                    if start > end or end - start > 1000:
                        return False, [], f"Invalid range {part} (max 1000 ports)"
                    ports.extend(range(start, end + 1))
                else:
                    ports.append(int(part))
        except ValueError as e:
            return False, [], f"Invalid port format: {e}"

        invalid = [p for p in ports if not (1 <= p <= 65535)]
        if invalid:
            return False, [], f"Invalid port numbers: {invalid[:5]}"

        return True, ports, ""

    def create_forward(self, port: int) -> Tuple[bool, str]:
        """Add a port forward."""
        if not self.config:
            return False, "No tunnel configuration provided"

        if port in self.config.forwarded_ports:
            return False, f"Port {port} already in forwarded list"

        # Check if port is already in use by a non-haproxy process
        if self._is_port_listening(port):
            process_info = self._get_port_process(port)
            if process_info and "haproxy" not in process_info.lower():
                return False, f"Port {port} is already in use by: {process_info}"

        self.config.add_port(port)
        config = self._generate_haproxy_config()

        if not self._write_config_file(config):
            # Rollback
            self.config.remove_port(port)
            return False, "Failed to write HAProxy configuration"

        if not self._reload_haproxy():
            return False, "Failed to reload HAProxy"

        return True, f"Port forward for port {port} created successfully."

    def remove_forward(self, port: int) -> Tuple[bool, str]:
        """Remove a single port forward."""
        if not self.config:
            return False, "No tunnel configuration provided"

        if port not in self.config.forwarded_ports:
            return False, f"Port {port} is not in forwarded list"

        self.config.remove_port(port)
        current_config = self._generate_haproxy_config()

        if not self._write_config_file(current_config):
            # Rollback
            self.config.add_port(port)
            return False, "Failed to update HAProxy configuration"

        if not self._reload_haproxy():
            return False, "Failed to reload HAProxy"

        return True, f"Port forward for {port} removed"

    def validate_and_reload(self) -> Tuple[bool, str]:
        """Validate generated HAProxy config and reload."""
        try:
            config = self._generate_haproxy_config()
            if not config:
                return False, "No HAProxy configuration generated"

            if not self._write_config_file(config):
                return False, "HAProxy configuration write/validation failed"

            if not self._reload_haproxy():
                return False, "HAProxy reload failed"

            return True, "HAProxy configuration validated and reloaded successfully"
        except Exception as e:
            return False, f"Error during validate_and_reload: {e}"

    def add_multiple_forwards(self, ports_str: str) -> Tuple[bool, str]:
        """Add multiple port forwards from comma-separated string or range."""
        ok, ports, err = self._parse_ports(ports_str)
        if not ok:
            return False, err

        results = []
        active_ports = []
        inactive_ports = []

        for port in ports:
            success, msg = self.create_forward(port)
            if success:
                active_ports.append(port)
                results.append(f"✓ Port {port}: ACTIVE")
            else:
                inactive_ports.append(port)
                results.append(f"✗ Port {port}: {msg}")

        if active_ports and inactive_ports:
            results.append(f"\nSummary: {len(active_ports)} activated, {len(inactive_ports)} failed")
        elif active_ports:
            results.append(f"\nAll {len(active_ports)} port(s) activated successfully")
        elif inactive_ports:
            results.append(f"\nAll {len(inactive_ports)} port(s) failed")

        return True, "\n".join(results)

    def remove_multiple_forwards(self, ports_str: str) -> Tuple[bool, str]:
        """Remove multiple port forwards from comma-separated string or range."""
        ok, ports, err = self._parse_ports(ports_str)
        if not ok:
            return False, err

        results = []
        for port in ports:
            success, msg = self.remove_forward(port)
            results.append(f"Port {port}: {msg}")

        return True, "\n".join(results)

    def list_forwards(self) -> List[Dict]:
        """List all configured port forwards from all tunnels."""
        forwards = []
        cm = ConfigManager()
        tunnels = cm.get_all_tunnels()

        for tunnel in tunnels:
            remote_ip = getattr(tunnel, 'remote_forward_ip', None)
            if not remote_ip:
                continue
            for port in tunnel.forwarded_ports:
                forwards.append({
                    "port": port,
                    "tunnel": tunnel.name,
                    "remote": f"{remote_ip}:{port}",
                    "active": self._is_port_listening(port),
                    "active_sessions": 0,
                    "stats": {}
                })

        return forwards

    async def start_all_forwards(self) -> Tuple[bool, str]:
        """Start all configured port forwards."""
        cm = ConfigManager()
        tunnels = cm.get_all_tunnels()

        has_forwards = any(t.forwarded_ports for t in tunnels)
        if not has_forwards:
            return True, "No port forwards configured"

        config = self._generate_haproxy_config()
        if not self._write_config_file(config):
            return False, "Failed to write/validate HAProxy configuration"

        try:
            result = subprocess.run(
                ["systemctl", "restart", "haproxy"],
                capture_output=True, timeout=15, text=True
            )

            if result.returncode != 0:
                stderr_msg = result.stderr.strip() if result.stderr else "Unknown error"
                return False, f"Failed to start HAProxy: {stderr_msg}"

            self.running = True
            all_ports = set()
            for tunnel in tunnels:
                all_ports.update(tunnel.forwarded_ports)
            ports_str = ", ".join(sorted(str(p) for p in all_ports))
            msg = f"HAProxy started with ports: {ports_str}" if ports_str else "HAProxy started"
            logger.info(msg)
            return True, msg

        except subprocess.TimeoutExpired:
            return False, "Timeout starting HAProxy"
        except Exception as e:
            logger.error(f"Exception in start_all_forwards: {e}")
            return False, f"Error starting HAProxy: {e}"

    async def stop_all_forwards(self) -> Tuple[bool, str]:
        """Stop all configured port forwards."""
        try:
            subprocess.run(
                ["systemctl", "stop", "haproxy"],
                capture_output=True, timeout=10
            )
            self.running = False
            return True, "HAProxy stopped"
        except Exception as e:
            return False, f"Error stopping HAProxy: {e}"

    async def restart_all_forwards(self) -> Tuple[bool, str]:
        """Restart all configured port forwards."""
        await self.stop_all_forwards()
        import asyncio
        await asyncio.sleep(1)
        return await self.start_all_forwards()


# Backward compatibility alias
ForwardManager = HAProxyManager
